### ISSUE TITLE
hey i have a issue with automation track with ETK

### ISSUE THREAD

**Issue by susmanPL** [r3eckon/BNG-BeamLegalRacing#25] opened 2024-02-17 14:31 UTC
well it pops me this issue of 
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/105125046/426347be-48b3-49cc-b6f4-1bd89574d04e)

**Comment by r3eckon** [comment] 2024-02-17 15:32
I don't get this issue, if it's the issue I think it is it should be fixed in the latest version of the mod. If you haven't yet try updating the mod. If you think you're on the right version try to reinstall in a clean userfolder. If that still doesn't work send me a screenshot of the console after the error happened because that error message doesn't have enough information.

**Comment by susmanPL** [comment] 2024-02-19 23:47
on other track the same happens 
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/105125046/66887ecd-0f9c-4ee1-89a4-b8f9f1defd40)

**Comment by susmanPL** [comment] 2024-02-20 13:22
after second reinstall
 ![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/105125046/1df1407a-0381-4393-a1ff-9f7c375b3b92)|
 
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/105125046/b239c7a0-4dd7-41c5-9a28-fc5c69dad193)
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/105125046/b2c4a602-08e1-4c57-99a7-1fb41c15e5ea)

**Comment by r3eckon** [comment] 2024-02-20 15:10
This error is caused by gas station display loading but latest version contains code to avoid loading gas station displays for maps that don't have them.

You're either not using the latest version of the mod or you have old mod files conflicting with the update. Don't just reinstall the mod in your current userfolder, install in a **clean userfolder** and carefully follow the instructions. This mod can't be installed as a zip, if you have the zip archive in your mod folder delete it.

**Closed by r3eckon** 2024-02-20 15:10 UTC

**Comment by susmanPL** [comment] 2024-02-20 16:12
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/105125046/8708205e-ce15-47fe-849d-7b5eef5ddf1d)
![image](https://github.com/r3eckon/BNG-BeamLegalRacing/assets/105125046/db30d7f1-8d77-41ac-8cd3-6a768c75e849)

this is all i have and it was my first time installing the mod so i didn't had the old release but i guess it could be done by the old releases that are in the folder named Old Releases
