### ISSUE TITLE
Mod wont work, and somehow made it so all the maps with beamlr compatibility had infinite loading

### ISSUE THREAD

**Issue by jk4182** [r3eckon/BNG-BeamLegalRacing#20] opened 2023-12-21 01:56 UTC
Not sure how this happend but it did, i installed it corrrectly

**Comment by r3eckon** [comment] 2023-12-21 02:30
Sounds like your game isn't up to date. I tested the mod with a clean install of 0.31.1 on a different computer and it works as expected. Are you using the latest version of the game and mod? If not that's likely the cause of your problem. Otherwise try to verify game files from steam, then back up your current userfolder to save your custom configs and try to install in a clean userfolder.

**Comment by jk4182** [comment] 2023-12-21 22:20
I think I could have installed it wrong since I did it by documents and not appdata

**Comment by r3eckon** [comment] 2023-12-22 01:52
Use the game launcher to find your userfolder. There's a link to a BeamNG website article on how to find your userfolder in the install instructions.

**Comment by jk4182** [comment] 2023-12-22 01:56
Is there a way I can install a clean copy of the game without steam adding the files I added manually because I installed the mod wrong and It'd be effort to hunt down every file

**Comment by r3eckon** [comment] 2023-12-22 02:11
Not sure what you mean by "steam adding the files I added manually" steam shouldn't add anything but original game files when you install. You shouldn't use the steam folder to install mods, though it can work, that's what the userfolder is for. In any case this isn't a problem with the mod so I'll close this issue. I suggest you head to the BeamNG forum if you need further help with your game install. Once you have a clean install, if you carefully follow BeamLR's install instructions it should work as expected.

**Closed by r3eckon** 2023-12-22 02:11 UTC
