### ISSUE TITLE
The game crashes when I sell a car at home

### ISSUE THREAD

**Issue by MauroKkkk** [r3eckon/BNG-BeamLegalRacing#56] opened 2024-09-25 13:52 UTC
Every time I make changes to a car and try to sell it in the garage, the car is sold and the other one that should appear simply breaks the game.

**Comment by MauroKkkk** [comment] 2024-09-25 13:53
[beamng.log](https://github.com/user-attachments/files/17131997/beamng.log)
[beamng-dxDiag.txt](https://github.com/user-attachments/files/17131999/beamng-dxDiag.txt)
[beamng-launcher.1.log](https://github.com/user-attachments/files/17132001/beamng-launcher.1.log)
[beamng-launcher.log](https://github.com/user-attachments/files/17132002/beamng-launcher.log)

**Comment by r3eckon** [comment] 2024-09-26 14:29
The error seems to be caused by frame delay that works on my PC but doesn't work for everyone else, I've already moved this function to onVehicleResetted hook that should work for everyone so it should be fixed in next version. After it releases don't bring back broken save files. Reset your career and start from scratch, cheat yourself money if you want to rebuild the cars you had. 

If it happens again after next update on a clean start reopen the issue and attach new log files.

**Closed by r3eckon** 2024-09-26 14:29 UTC
