### ISSUE TITLE
Fuel type missing

### ISSUE THREAD

**Issue by flappelapper** [r3eckon/BNG-BeamLegalRacing#27] opened 2024-03-18 20:28 UTC
I've had the same bug happen twice across about 5 hours of gameplay. Whenever I'm changing stuff on the cars, some action is making the car file just delete 'fueltype'. The string simply disappears, the gas integer goes to 0 and fuelratio goes to 0,0,1. 

This makes the UI say the tank is full, and that I put in the wrong fuel type, thus rendering the car undrivable (I don't see how to get my car to a fuel station to put different fuel in when theres no option to be towed there?)

**Comment by r3eckon** [comment] 2024-03-19 06:15
I can't recreate this bug, do you have part mods that include engines? If so it's possible the jbeam data for the modded engines doesn't contain a required fuel type which would bug the fuel system.

**Comment by flappelapper** [comment] 2024-03-19 19:47
I actually deleted all my mods and did a clean reinstall of the game before installing BeamLR, just to make sure it would run as smooth as possible.

My repo mods are ETK700, ETK800 coupe, the new european H-series, and the Vivace Emousse.

Manual installed mods are partimages, nordschleife, ks_nord addon and remastered engine sounds.

The only one I can see being a problem is remastered engine sounds, but it doesn't change any engines parts or anything, just sounds.

This happened on both Roamer and Vivace btw.

**Comment by r3eckon** [comment] 2024-03-20 01:56
I just checked the remastered engine sounds mod and it doesn't seem to change the variable needed for fuel system to work. If you get this bug again check the console for errors and if there are any upload your log file (userfolder/beamng.log) here so I can check what's going on.

**Comment by r3eckon** [comment] 2024-06-23 17:36
Closing this due to lack of updates, assuming the issue is fixed. If not I need log files to do anything else.

**Closed by r3eckon** 2024-06-23 17:36 UTC
